Fixes
fix some flags to be the appropriate value

fixed the nuclear positions that are fed into the fermi neural net

replaced some of the numpy calls with torch calls in monte_carlo

fix fnn.py error
File "DNN-SE/fnn.py", line 66, in preprocess
    eN_vectors = np.array([[i-j for j in self.nuclei_positions] for i in electron_positions])
ValueError: only one element tensors can be converted to Python scalars

which is basically saying that the list comprehension
is attempting to convert the (x,y,z) list into a single python scalar
but that isn't allowed