Completed - walkers
Implemented basic `generate_electron_position_vector`

Added a stripped down `system.py` using namedtuples
although I think it would be better to change them to Simplenamespace
in the future because we DO actually need mutability

Updated the `monte_carlo.py` to agree with the correct shape of the
`walkers`

You can currently run the driver as follows:
 - python3 driver.py
 - python3 driver.py hydrogen
 - python3 driver.py chain 2      (or some other integer)
 - python3 driver.py methane

there are a lot of extraneous print statements at the moment
once `elements`, `system`, `units` and other modules are
fully implemented they can be removed

The current traceback whose fix is in will's court:

Traceback (most recent call last):
  File "driver.py", line 752, in <module>
    main(molecule, spins)
  File "driver.py", line 695, in main
    mcmc_object = prepare_mcmc(mcmc_config, network_object, init_means, precision)
  File "driver.py", line 634, in prepare_mcmc
    mcmc_object = MonteCarlo(
  File "monte_carlo.py", line 106, in __init__
    self.psi = self.compute_psi()
  File "monte_carlo.py", line 113, in compute_psi
    return self.net.forward(self.walkers)
  File "fnn.py", line 86, in forward
    if (electron_positions != None) and (nuclei_positions != None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()