Fix - initialization of network
unclear to me if I actually need to provide valid `electron_positions`
and `nuclei_positions` when initializing the `fnn.py`

Next step is to get the hamiltonian operators from andrew as that is the
next error in execution:

  File "/DNN-SE/train.py", line 33, in __init__
    self.kinetic, self.potential = hamiltonian_operators
TypeError: cannot unpack non-iterable NoneType object